# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptctl" do
  name "promptctl"
  desc "CLI toolkit that transforms raw intent into structured, optimized prompts"
  homepage "https://prompt-ctl.com"
  version "0.8.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptctl"

  on_macos do
    on_intel do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "295bb0ad3422c484612e95669405815768e86a6a23bcf84aa3268d066af92e48"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "ad0e3d2d77d989e61e09f9ea740177d537b972194d2c0dd50eb1bd73b991e289"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "fd5d04854d7bab537ea9cf35d4457ff9cd245571b7aef4fcaff4386329dd114e"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "0f8f4e007772f49ed6a047c3998d6d71e9e66dfba509eeae2e37af8d37a89d50"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/promptctl"]
    end
  end

  # No zap stanza required
end
