# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptctl" do
  name "promptctl"
  desc "CLI toolkit that transforms raw intent into structured, optimized prompts"
  homepage "https://prompt-ctl.com"
  version "0.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptctl"

  on_macos do
    on_intel do
      url "https://github.com/oleg-koval/promptctl/releases/download/v#{version}/promptctl_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl/"
      sha256 "8fbb0fc7447e48af56c480101eaa0e4b7ecd154418f2167857e78a9456db74fa"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl/releases/download/v#{version}/promptctl_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl/"
      sha256 "44ac6cd24ba8077790a1b8dbb323c9a906be4e1665ac7daec0bf5fc34372c945"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oleg-koval/promptctl/releases/download/v#{version}/promptctl_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl/"
      sha256 "d647c64067ce07f361c598bfa83e6d5bdb23410f7c95352f1a0c4f6f41938c36"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl/releases/download/v#{version}/promptctl_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl/"
      sha256 "8244469adbf02bd20b8780b6a92d4f483e8ed421a64e20c6e3c3885f3abbd7c2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/promptctl"]
    end
  end

  # No zap stanza required
end
