# This file was generated by GoReleaser. DO NOT EDIT.
cask "promptctl" do
  name "promptctl"
  desc "CLI toolkit that transforms raw intent into structured, optimized prompts"
  homepage "https://prompt-ctl.com"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "promptctl"

  on_macos do
    on_intel do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "361a9cb13863905a394038dab402a1a732a7f76c2afa596ffec28e4226dabcc2"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "fc3a5d9b584167092482f4b70ca7b58c4ebca231a71dfcdb27d5a760fc3a7042"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "6b533df3d51b8292d78c1fe78dab19d210b8317984e3b8ced8e71068ecc9f0da"
    end
    on_arm do
      url "https://github.com/oleg-koval/promptctl-releases/releases/download/v#{version}/promptctl_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/oleg-koval/promptctl-releases/"
      sha256 "0e4ecd9d8990be38f83b57de394095c1658f34a09efc0c1a1138d886945b0df0"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/promptctl"]
    end
  end

  # No zap stanza required
end
