# This file was generated by GoReleaser. DO NOT EDIT.
cask "veto" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "12c791d330e1fad6ed1f75414332be1e0150a625d76f5035dea42a6a4e551967"
      url "https://github.com/oleg-koval/veto/releases/download/v#{version}/veto_#{version}_darwin_amd64.tar.gz"
      rename "veto_0.1.0_darwin_amd64/veto", "veto"
    end
    on_arm do
      sha256 "e7470730db8b526aa3f9cd46c42bfcf490d858b294802152d4c893dfa878efc4"
      url "https://github.com/oleg-koval/veto/releases/download/v#{version}/veto_#{version}_darwin_arm64.tar.gz"
      rename "veto_0.1.0_darwin_arm64/veto", "veto"
    end
  end

  on_linux do
    on_intel do
      sha256 "1abe1cd10205c2f87fb20a62b696d701fb3aea667884b8d33bd9109866da80f5"
      url "https://github.com/oleg-koval/veto/releases/download/v#{version}/veto_#{version}_linux_amd64.tar.gz"
      rename "veto_0.1.0_linux_amd64/veto", "veto"
    end
    on_arm do
      sha256 "fc15414a9cbd659571c9894d49a422c17d4059ad97443cea3e59f30d385defe8"
      url "https://github.com/oleg-koval/veto/releases/download/v#{version}/veto_#{version}_linux_arm64.tar.gz"
      rename "veto_0.1.0_linux_arm64/veto", "veto"
    end
  end

  name "veto"
  desc "Cost-aware AI model router with structured admission decisions"
  homepage "https://github.com/oleg-koval/veto"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "veto"

  # No zap stanza required

end
