# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptctl < Formula
  desc "CLI toolkit that transforms raw intent into structured, optimized prompts"
  homepage "https://prompt-ctl.com"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prompt-ctl/promptctl/releases/download/v1.3.0/promptctl_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "e431cf8b13c3e1ddf78d8540df57187a93e9593db49c3f0b174116567edc8a2b"

      define_method(:install) do
        bin.install "promptctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prompt-ctl/promptctl/releases/download/v1.3.0/promptctl_1.3.0_Darwin_arm64.tar.gz"
      sha256 "3efe520d1ed276716c78925e744e2c955c2cf0620064a6923c16506d2d0b1e0f"

      define_method(:install) do
        bin.install "promptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prompt-ctl/promptctl/releases/download/v1.3.0/promptctl_1.3.0_Linux_x86_64.tar.gz"
      sha256 "94733aa2bbebd9c206243510f88ce7477cc9a260f22c5915be72819d09f8f73c"
      define_method(:install) do
        bin.install "promptctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prompt-ctl/promptctl/releases/download/v1.3.0/promptctl_1.3.0_Linux_arm64.tar.gz"
      sha256 "d6b932dd37b5b05b0c24016e191bb5a2ff8207f558ee03feeb4d7feee9757fb0"
      define_method(:install) do
        bin.install "promptctl"
      end
    end
  end

  test do
    system "#{bin}/promptctl --version"
  end
end
