# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Promptctl < Formula
  desc "CLI toolkit that transforms raw intent into structured, optimized prompts"
  homepage "https://prompt-ctl.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/prompt-ctl/prompt-ctl/releases/download/v0.1.2/promptctl_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "1165bf928d8c7a58999b24b82d653df1f9a6bbe2ec81f7d8e75769801d26231b"

      define_method(:install) do
        bin.install "promptctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/prompt-ctl/prompt-ctl/releases/download/v0.1.2/promptctl_0.1.2_Darwin_arm64.tar.gz"
      sha256 "36ab4b1049aa860fd6660eea77919f8938aa5440a14d9971a5a7521cc62f85ed"

      define_method(:install) do
        bin.install "promptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/prompt-ctl/prompt-ctl/releases/download/v0.1.2/promptctl_0.1.2_Linux_x86_64.tar.gz"
      sha256 "57afe0aaabd45a9b15c12f70065a8a286faff5e4dee87c9a5361e5ded0bf83f4"
      define_method(:install) do
        bin.install "promptctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/prompt-ctl/prompt-ctl/releases/download/v0.1.2/promptctl_0.1.2_Linux_arm64.tar.gz"
      sha256 "00ff316837a9723bc231c17a23e72e4eca9230ae5c2949009fde4c6e7d2a0b5a"
      define_method(:install) do
        bin.install "promptctl"
      end
    end
  end

  test do
    system "#{bin}/promptctl --version"
  end
end
